-- TCH Patient 360 - Deployment Verification

USE ROLE TCH_PATIENT_360_ROLE;
USE WAREHOUSE TCH_ANALYTICS_WH;
USE DATABASE TCH_PATIENT_360_POC;

-- Verify raw source tables
SELECT 'EPIC.PATIENTS' AS object_name, COUNT(*) AS row_count FROM EPIC.PATIENTS
UNION ALL SELECT 'EPIC.ENCOUNTERS', COUNT(*) FROM EPIC.ENCOUNTERS
UNION ALL SELECT 'WORKDAY.PROVIDERS', COUNT(*) FROM WORKDAY.PROVIDERS
UNION ALL SELECT 'WORKDAY.DEPARTMENTS', COUNT(*) FROM WORKDAY.DEPARTMENTS
UNION ALL SELECT 'ORACLE_ERP.ENCOUNTER_FINANCIALS', COUNT(*) FROM ORACLE_ERP.ENCOUNTER_FINANCIALS
UNION ALL SELECT 'SALESFORCE.PATIENT_PORTAL_ACTIVITY', COUNT(*) FROM SALESFORCE.PATIENT_PORTAL_ACTIVITY
ORDER BY object_name;

-- Verify Dynamic Tables
SELECT table_name, target_lag, last_refresh_time, refresh_mode
FROM INFORMATION_SCHEMA.TABLES
WHERE table_type = 'DYNAMIC TABLE'
ORDER BY table_name;

-- Multi-source integration sanity check
SELECT 
    COUNT(DISTINCT pm.patient_id) AS total_patients,
    COUNT(DISTINCT ff.patient_key) AS patients_with_financial,
    COUNT(DISTINCT ef.patient_key) AS patients_with_engagement
FROM CONFORMED.PATIENT_MASTER pm
LEFT JOIN CONFORMED.FINANCIAL_FACT ff ON pm.patient_key = ff.patient_key
LEFT JOIN CONFORMED.ENGAGEMENT_FACT ef ON pm.patient_key = ef.patient_key;

-- Cortex services
SHOW CORTEX SEARCH SERVICES;
SHOW STREAMLITS;


